apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotstar-clone
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/useryash01/hotstar-clone-devsecops.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
