pipeline {
    agent any

    tools {
        nodejs 'NODE-JS22'
    }

    stages {

        stage('Check Versions') {
            steps {
                sh 'node --version'
                sh 'npm --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app') {
                    sh '''
                    npm config set fetch-retries 5
                    npm config set fetch-retry-factor 10
                    npm config set fetch-retry-mintimeout 20000
                    npm config set fetch-retry-maxtimeout 120000
                    npm install
                    '''
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('app') {
                    sh 'CI=false npm run build'
                }
            }
        }
    }
}
